file_format: "1"
id: temper
name: Chocofi Temper
type: shield
url: https://github.com/raeedcho/chocofi-temper
requires: [pro_micro]
exposes: [nice_views]
features:
  - keys
  - display
siblings:
  - temper_left
  - temper_right
  - temper_dongle
