# This file generates the GitHub Actions matrix
---
include:
#Dongle
  - board: seeeduino_xiao_ble  
    shield: temper_central_dongle_128x32 dongle_display
    artifact-name: temper_central_dongle_128x32
  - board: seeeduino_xiao_ble  
    shield: temper_central_dongle_128x64 dongle_display
    artifact-name: temper_central_dongle_128x64
  - board: seeeduino_xiao_ble  
    shield: temper_central_dongle_128x64 
    artifact-name: temper_central_dongle_no_display


#Temper
  - board: nice_nano_v2
    shield: temper_central_left nice_view_adapter nice_view
    artifact-name: temper_central_left
  - board: nice_nano_v2
    shield: temper_peripheral_left nice_view_adapter nice_view
    artifact-name: temper_peripheral_left
  - board: nice_nano_v2
    shield: temper_peripheral_right nice_view_adapter nice_view
    artifact-name: temper_peripheral_right
  
#Reset:
  - board: seeeduino_xiao_ble
    shield: settings_reset
  - board: nice_nano_v2
    shield: settings_reset