draw_config:
  key_w: 60
  key_h: 56
  split_gap: 30.0
  combo_w: 28
  combo_h: 26
  key_rx: 6.0
  key_ry: 6.0
  dark_mode: auto
  n_columns: 1
  separate_combo_diagrams: false
  combo_diagrams_scale: 2
  inner_pad_w: 2.0
  inner_pad_h: 2.0
  outer_pad_w: 30.0
  outer_pad_h: 56.0
  line_spacing: 1.2
  arc_radius: 6.0
  append_colon_to_layer_header: false
  small_pad: 2.0
  legend_rel_x: 0.0
  legend_rel_y: 0.0
  draw_key_sides: true
  key_side_pars:
    rel_x: 0.0
    rel_y: 4.0
    rel_w: 12.0
    rel_h: 12.0
    rx: 4.0
    ry: 4.0
  svg_extra_style: "svg.keymap {\n  font-family: Helvetica Neue, Helvetica, Arial,\
    \ sans-serif;\n  font-size: 10px;\n  font-weight: bold;\n}\n\ntext.label {\n \
    \ stroke: #dfdfde;\n  stroke-width: 12;\n  stroke-linejoin: round;\n}\n\nrect.combo,\
    \ rect.combo-separate {\n  opacity: 0.95;\n  stroke: #c9cccf;\n  stroke-width:\
    \ 0.5;\n  fill: #d7eaed;\n}\npath.combo {\n  stroke-dasharray: 4, 4;\n  stroke-opacity:\
    \ 0.7;\n}\n\nrect.held, rect.combo.held {\n  fill: #ebdada;\n}\n\n.trans.tap,\
    \ .ghost.tap {\n  opacity: 0.5;\n}\n\n.shifted {\n  translate: -9px 3px;\n  opacity:\
    \ 0.3;\n}\n\n.toggle.shifted {\n  translate: -12px 17px;\n  opacity: 1.0;\n}\n\
    .toggle.hold {\n  translate: 12px -25px;\n}\n\n.text_with_symbol.tap {\n  translate:\
    \ -1px 1px;\n}\n.text_with_symbol.shifted {\n  translate: 8px 13px;\n  font-size:\
    \ 8px;\n  opacity: 1.0;\n} \n\n.combo.text_with_symbol.tap {\n  translate: -1px\
    \ 1px;\n}\n.combo.text_with_symbol.shifted {\n  translate: 7px 5px;\n  font-size:\
    \ 8px;\n  opacity: 1.0;\n}\n"
  footer_text: ''
  shrink_wide_legends: 7
  style_layer_activators: true
  glyph_tap_size: 14
  glyph_hold_size: 8
  glyph_shifted_size: 8
  glyphs: {}
  glyph_urls:
    tabler: https://unpkg.com/@tabler/icons/icons/outline/{}.svg
    tablerf: https://unpkg.com/@tabler/icons/icons/filled/{}.svg
    mdi: https://raw.githubusercontent.com/Templarian/MaterialDesign-SVG/master/svg/{}.svg
    mdil: https://raw.githubusercontent.com/Pictogrammers/MaterialDesignLight/master/svg/{}.svg
    material: https://fonts.gstatic.com/s/i/short-term/release/materialsymbolsoutlined/{}/default/48px.svg
  use_local_cache: true
parse_config:
  preprocess: true
  skip_binding_parsing: false
  raw_binding_map:
    '&sys_reset': $$mdi:backup-restore$$
    '&bootloader': $$mdi:progress-download$$
    '&hml LA(LCTRL) TAB': $$mdi:keyboard-tab$$
    '&hml_repeat LS(LCTRL) 0': $$mdi:repeat$$
    '&key_repeat': $$mdi:repeat$$
    '&win_sleep': $$mdi:sleep$$
    '&caps_word': $$mdi:caps-lock$$
    '&mt LA(F4) LC(W)': $$mdi:close-box-outline$$
    '&alt_tabber': $$mdi:swap-horizontal$$
    '&kns_lock': $$mdi:apple-keyboard-caps$$
    '&dgrv_macro': '``'
    '&brc_macro': '[]'
    '&par_macro': ()
    '&bkt_macro': '{}'
    '&lgt_macro': <>
    '&kp LC(BSPC)': $$mdi:backspace$$
    '&kp LC(DEL)': $$mdi:backspace-reverse$$
    '&kp LS(TAB)': $$mdi:keyboard-tab-reverse$$
    '&kp LC(TAB)': $$mdi:arrow-right-bold-box$$
    '&kp LC(LS(TAB))': $$mdi:arrow-left-bold-box$$
    '&kp LC(LG(LEFT))': $$mdi:arrow-left-bold-box-outline$$
    '&kp LC(LG(RIGHT))': $$mdi:arrow-right-bold-box-outline$$
    '&kp LC(LS(LALT))': $$mdi:star-three-points-outline$$
    '&kp LC(LS(LA(LGUI)))': $$mdi:star-four-points-outline$$
    '&kp LC(HOME)': $$mdi:format-vertical-align-top$$
    '&kp LC(END)': $$mdi:format-vertical-align-bottom$$
    '&kp LC(INS)': $$mdi:content-copy$$
    '&kp LC(C)': $$mdi:content-copy$$
    '&kp LS(INS)': $$mdi:content-paste$$
    '&kp LC(V)': $$mdi:content-paste$$
    '&kp LS(DEL)': $$mdi:content-cut$$
    '&kp LC(X)': $$mdi:content-cut$$
    '&kp LC(S)': $$mdi:content-save$$
    '&kp LC(DE_Z)': $$mdi:undo$$
    '&kp LC(DE_Y)': $$mdi:redo$$
    '&kp LC(LS(DE_Z))': $$mdi:redo$$
    '&kp LC(F)': $$mdi:text-search$$
    '&kp LC(W)': $$mdi:close-box-outline$$
    '&kp LA(F4)': $$mdi:pistol$$
    '&kp LC(DE_PLUS)': $$mdi:magnify-plus-outline$$
    '&kp LC(DE_MINUS)': $$mdi:magnify-minus-outline$$
    '&kp LC(N0)': $$mdi:magnify-remove-outline$$
    '&kp LG(L)': $$mdi:lock-outline$$
    '&td_sqt_dqt':
      tap: ''''
      shifted: '"'
    '&kp DE_COMMA':
      tap: ','
      shifted: ;
    '&kp DE_DOT':
      tap: .
      shifted: ':'
    '&out OUT_BLE': $$mdi:bluetooth$$
    '&out OUT_USB': $$mdi:usb$$
    '&out OUT_TOG':
      tap: $$mdi:toggle-switch$$
      hold: $$mdi:bluetooth$$
      shifted: $$mdi:usb$$
      type: toggle
    '&bt BT_CLR':
      tap: $$mdi:bluetooth$$
      shifted: $$mdi:cogs$$
      type: text_with_symbol
    '&bts 0':
      tap: $$mdi:bluetooth-connect$$
      shifted: '0'
      type: text_with_symbol
    '&bts 1':
      tap: $$mdi:bluetooth-connect$$
      shifted: '1'
      type: text_with_symbol
    '&bts 2':
      tap: $$mdi:bluetooth-connect$$
      shifted: '2'
      type: text_with_symbol
    '&bts 3':
      tap: $$mdi:bluetooth-connect$$
      shifted: '3'
      type: text_with_symbol
    '&bts 4':
      tap: $$mdi:bluetooth-connect$$
      shifted: '4'
      type: text_with_symbol
    '&bt BT_SEL 0':
      tap: $$mdi:bluetooth-connect$$
      shifted: '0'
      type: text_with_symbol
    '&bt BT_SEL 1':
      tap: $$mdi:bluetooth-connect$$
      shifted: '1'
      type: text_with_symbol
    '&bt BT_SEL 2':
      tap: $$mdi:bluetooth-connect$$
      shifted: '2'
      type: text_with_symbol
    '&bt BT_SEL 3':
      tap: $$mdi:bluetooth-connect$$
      shifted: '3'
      type: text_with_symbol
    '&bt BT_SEL 4':
      tap: $$mdi:bluetooth-connect$$
      shifted: '4'
      type: text_with_symbol
    '&bt BT_DISC 0':
      tap: $$mdi:bluetooth-off$$
      shifted: '0'
      type: text_with_symbol
    '&bt BT_DISC 1':
      tap: $$mdi:bluetooth-off$$
      shifted: '1'
      type: text_with_symbol
    '&bt BT_DISC 2':
      tap: $$mdi:bluetooth-off$$
      shifted: '2'
      type: text_with_symbol
    '&bt BT_DISC 3':
      tap: $$mdi:bluetooth-off$$
      shifted: '3'
      type: text_with_symbol
    '&bt BT_DISC 4':
      tap: $$mdi:bluetooth-off$$
      shifted: '4'
      type: text_with_symbol
    '&mkp LCLK': $$mdi:cursor-default-click-outline$$
    '&mkp RCLK': $$mdi:cursor-default-click$$
    '&mkp MB3':
      tap: $$mdi:cursor-default-click-outline$$
      shifted: 3
      type: text_with_symbol
    '&mkp MB4':
      tap: $$mdi:cursor-default-click-outline$$
      shifted: 4
      type: text_with_symbol
    '&mkp MB5':
      tap: $$mdi:cursor-default-click-outline$$
      shifted: 5
      type: text_with_symbol
    '&tb_mo_scroll':
      tap: $$mdi:billiards$$
      shifted: $$mdi:arrow-up-down$$
      type: text_with_symbol
    '&tb_tg_scroll':
      tap: $$mdi:billiards$$
      shifted: $$mdi:arrow-up-down$$
      hold: $$mdi:toggle-switch$$
      type: text_with_symbol
    '&tbs_mt 0 0':
      tap: $$mdi:billiards$$
      shifted: $$mdi:arrow-up-down$$
      hold: $$mdi:toggle-switch$$
      type: text_with_symbol
    '&tb_bootloader':
      tap: $$mdi:billiards$$
      shifted: $$mdi:progress-download$$
      type: text_with_symbol
    '&tb_cyc_dpi':
      tap: $$mdi:billiards$$
      shifted: $$mdi:speedometer$$
      type: text_with_symbol
  sticky_label: $$mdi:circle-small$$
  toggle_label: $$mdi:toggle-switch$$
  tap_toggle_label: tap-toggle
  trans_legend:
    tap: $$mdi:chevron-down$$
    type: trans
  mark_alternate_layer_activators: false
  modifier_fn_map:
    left_ctrl: Ctl
    right_ctrl: Ctl
    left_shift: Sft
    right_shift: Sft
    left_alt: Alt
    right_alt: AGr
    left_gui: Gui
    right_gui: Gui
    keycode_combiner: '{mods}+ {key}'
    mod_combiner: '{mod_1}+{mod_2}'
    special_combinations:
      left_ctrl+left_alt+left_gui+left_shift: Hyper
      left_ctrl+left_alt+left_shift: Meh
  qmk_remove_keycode_prefix:
  - KC_
  qmk_keycode_map:
    XXXXXXX: ''
    'NO': ''
    MINUS: '-'
    MINS: '-'
    EQUAL: '='
    EQL: '='
    LEFT_BRACKET: '['
    LBRC: '['
    RIGHT_BRACKET: ']'
    RBRC: ']'
    BACKSLASH: \
    BSLS: \
    NONUS_HASH: '#'
    NUHS: '#'
    SEMICOLON: ;
    SCLN: ;
    QUOTE: ''''
    QUOT: ''''
    GRAVE: '`'
    GRV: '`'
    COMMA: ','
    COMM: ','
    DOT: .
    SLASH: /
    SLSH: /
    TILDE: '~'
    TILD: '~'
    EXCLAIM: '!'
    EXLM: '!'
    AT: '@'
    HASH: '#'
    DOLLAR: $
    DLR: $
    PERCENT: '%'
    PERC: '%'
    CIRCUMFLEX: ^
    CIRC: ^
    AMPERSAND: '&'
    AMPR: '&'
    ASTERISK: '*'
    ASTR: '*'
    LEFT_PAREN: (
    LPRN: (
    RIGHT_PAREN: )
    RPRN: )
    UNDERSCORE: _
    UNDS: _
    PLUS: +
    LEFT_CURLY_BRACE: '{'
    LCBR: '{'
    RIGHT_CURLY_BRACE: '}'
    RCBR: '}'
    PIPE: '|'
    COLON: ':'
    COLN: ':'
    DOUBLE_QUOTE: '"'
    DQUO: '"'
    DQT: '"'
    LEFT_ANGLE_BRACKET: <
    LABK: <
    LT: <
    RIGHT_ANGLE_BRACKET: '>'
    RABK: '>'
    GT: '>'
    QUESTION: '?'
    QUES: '?'
  zmk_remove_keycode_prefix:
  - DE_
  zmk_keycode_map:
    LALT: ALT
    RALT: ALT
    SPACE: $$mdi:keyboard-space$$
    ESC: $$mdi:keyboard-esc$$
    ESCAPE: $$mdi:keyboard-esc$$
    RETURN: $$mdi:keyboard-return$$
    RET: $$mdi:keyboard-return$$
    BACKSPACE: $$mdi:backspace-outline$$
    BSPC: $$mdi:backspace-outline$$
    DELETE: $$mdi:backspace-reverse-outline$$
    DEL: $$mdi:backspace-reverse-outline$$
    LCTRL: $$mdi:apple-keyboard-control$$
    LEFT_CONTROL: $$mdi:apple-keyboard-control$$
    RCTRL: $$mdi:apple-keyboard-control$$
    RIGHT_CONTROL: $$mdi:apple-keyboard-control$$
    LSHFT: $$mdi:apple-keyboard-shift$$
    LSHIFT: $$mdi:apple-keyboard-shift$$
    LEFT_SHIFT: $$mdi:apple-keyboard-shift$$
    RSHFT: $$mdi:apple-keyboard-shift$$
    RSHIFT: $$mdi:apple-keyboard-shift$$
    RIGHT_SHIFT: $$mdi:apple-keyboard-shift$$
    LEFT_GUI: $$mdi:microsoft-windows$$
    RIGHT_GUI: $$mdi:microsoft-windows$$
    LGUI: $$mdi:microsoft-windows$$
    RGUI: $$mdi:microsoft-windows$$
    TAB: $$mdi:keyboard-tab$$
    CLCK: $$mdi:apple-keyboard-caps$$
    CAPS: $$mdi:apple-keyboard-caps$$
    CAPSLOCK: $$mdi:apple-keyboard-caps$$
    SCROLLLOCK: $$mdi:arrow-vertical-lock$$
    SLCK: $$mdi:arrow-vertical-lock$$
    SCLK: $$mdi:arrow-vertical-lock$$
    KP_NLCK: $$mdi:numeric-off$$
    KP_NUMBER_0: '0'
    KP_NUMBER_1: '1'
    KP_NUMBER_2: '2'
    KP_NUMBER_3: '3'
    KP_NUMBER_4: '4'
    KP_NUMBER_5: '5'
    KP_NUMBER_6: '6'
    KP_NUMBER_7: '7'
    KP_NUMBER_8: '8'
    KP_NUMBER_9: '9'
    PSCRN: $$mdi:monitor-screenshot$$
    PRINTSCREEN: $$mdi:monitor-screenshot$$
    PAUSE_BREAK: Pause Break
    C_PP: $$mdi:play-pause$$
    C_NEXT: $$mdi:skip-forward$$
    C_PREV: $$mdi:skip-backward$$
    C_MUTE: $$mdi:volume-mute$$
    C_VOL_UP: $$mdi:volume-plus$$
    C_VOL_DN: $$mdi:volume-minus$$
    C_BRI_UP: $$tabler:brightness-up$$
    C_BRI_DN: $$tabler:brightness-down$$
    C_POWER: $$mdi:power$$
    C_SLEEP: $$mdi:power-sleep$$
    C_AL_CALC: $$mdi:calculator$$
    UP: $$mdi:arrow-up$$
    DOWN: $$mdi:arrow-down$$
    LEFT: $$mdi:arrow-left$$
    RIGHT: $$mdi:arrow-right$$
    UP ARROW: $$mdi:arrow-up$$
    DOWN ARROW: $$mdi:arrow-down$$
    LEFT ARROW: $$mdi:arrow-left$$
    RIGHT ARROW: $$mdi:arrow-right$$
    LEFT_ALT: ALT
    RIGHT_ALT: ALT
    PG_UP: $$mdi:format-vertical-align-top$$
    PG_DN: $$mdi:format-vertical-align-bottom$$
    PAGE_UP: $$mdi:format-vertical-align-top$$
    PAGE_DOWN: $$mdi:format-vertical-align-bottom$$
    HOME: $$mdi:format-horizontal-align-left$$
    END: $$mdi:format-horizontal-align-right$$
    SECT: §
    DEG: °
    EURO: €
    A_UMLAUT: Ä
    AE: Ä
    U_UMLAUT: Ü
    UE: Ü
    O_UMLAUT: Ö
    OE: Ö
    SZ: ß
    ACUTE: ´
    EXCLAMATION: '!'
    EXCL: '!'
    AT_SIGN: '@'
    AT: '@'
    HASH: '#'
    POUND: '#'
    DOLLAR: $
    DLLR: $
    PERCENT: '%'
    PRCNT: '%'
    CARET: ^
    AMPERSAND: '&'
    AMPS: '&'
    ASTERISK: '*'
    ASTRK: '*'
    STAR: '*'
    LEFT_PARENTHESIS: (
    LPAR: (
    RIGHT_PARENTHESIS: )
    RPAR: )
    EQUAL: '='
    PLUS: +
    MINUS: '-'
    UNDERSCORE: _
    UNDER: _
    SLASH: /
    FSLH: /
    QUESTION: '?'
    QMARK: '?'
    BACKSLASH: \
    BSLH: \
    PIPE: '|'
    NON_US_BACKSLASH: \
    PIPE2: '|'
    NON_US_BSLH: '\'
    SEMICOLON: ;
    SEMI: ;
    COLON: ':'
    SINGLE_QUOTE: ''''
    SQT: ''''
    APOSTROPHE: ''''
    APOS: ''''
    DOUBLE_QUOTES: '"'
    DQT: '"'
    COMMA: ','
    LESS_THAN: <
    LT: <
    PERIOD: .
    DOT: .
    GREATER_THAN: '>'
    GT: '>'
    LEFT_BRACKET: '['
    LBKT: '['
    LEFT_BRACE: '{'
    LBRC: '{'
    RIGHT_BRACKET: ']'
    RBKT: ']'
    RIGHT_BRACE: '}'
    RBRC: '}'
    GRAVE: '`'
    TILDE: '~'
    NON_US_HASH: '#'
    NUHS: '#'
    TILDE2: '~'
  zmk_combos:
    kill:
      align: top
    caps:
      align: top
      offset: 1
    num_lock:
      align: top
  zmk_preamble: '#define KEYMAP_DRAWER'
  zmk_additional_includes: []
