layout: {qmk_keyboard: chocofi}
layers:
  DEF:
  - Q
  - W
  - E
  - R
  - T
  - Y
  - U
  - I
  - O
  - P
  - {t: A, h: LEFT GUI}
  - {t: S, h: '$$mdi:apple-keyboard-control$$'}
  - {t: D, h: RIGHT ALT}
  - {t: F, h: '$$mdi:apple-keyboard-shift$$'}
  - G
  - H
  - {t: J, h: '$$mdi:apple-keyboard-shift$$'}
  - {t: K, h: RIGHT ALT}
  - {t: L, h: '$$mdi:apple-keyboard-control$$'}
  - ;
  - Z
  - X
  - C
  - V
  - B
  - N
  - M
  - ','
  - .
  - /
  - $$mdi:keyboard-tab$$
  - {t: '$$mdi:backspace-reverse-outline$$', h: NUM}
  - $$mdi:keyboard-space$$
  - ENTER
  - {t: '$$mdi:backspace-outline$$', h: NAV}
  - FUN
  NUM:
  - '`'
  - '@'
  - '{'
  - '}'
  - '%'
  - '*'
  - '7'
  - '8'
  - '9'
  - '-'
  - ^
  - '#'
  - (
  - {t: ), h: '$$mdi:apple-keyboard-shift$$'}
  - $
  - {t: /, s: '|'}
  - {t: '4', h: '$$mdi:apple-keyboard-shift$$'}
  - '5'
  - '6'
  - +
  - ''''
  - '&'
  - '['
  - ']'
  - {t: '!', s: '|'}
  - .
  - '1'
  - '2'
  - '3'
  - '='
  - {t: '$$mdi:chevron-down$$', type: trans}
  - {type: held}
  - {t: '$$mdi:chevron-down$$', type: trans}
  - {t: '$$mdi:chevron-down$$', type: trans}
  - {t: '$$mdi:chevron-down$$', type: trans}
  - '0'
  NAV:
  - $$mdi:keyboard-esc$$
  - $$mdi:volume-mute$$
  - $$mdi:volume-minus$$
  - $$mdi:volume-plus$$
  - ''
  - ''
  - HOME
  - $$mdi:arrow-up$$
  - PAGE UP
  - ''
  - {t: LEFT GUI, h: '$$mdi:circle-small$$'}
  - {t: '$$mdi:apple-keyboard-control$$', h: '$$mdi:circle-small$$'}
  - {t: LEFT ALT, h: '$$mdi:circle-small$$'}
  - {t: '$$mdi:apple-keyboard-shift$$', h: '$$mdi:circle-small$$'}
  - ''
  - ''
  - $$mdi:arrow-left$$
  - $$mdi:arrow-down$$
  - $$mdi:arrow-right$$
  - ''
  - ''
  - $$mdi:skip-backward$$
  - $$mdi:play-pause$$
  - $$mdi:skip-forward$$
  - ''
  - ''
  - END
  - ''
  - PAGE DOWN
  - ''
  - {t: '$$mdi:chevron-down$$', type: trans}
  - ''
  - ''
  - ''
  - {type: held}
  - ''
  FUN:
  - $$mdi:progress-download$$
  - ''
  - PRINTSCREEN
  - '&win_sleep'
  - {t: '$$mdi:toggle-switch$$', h: '$$mdi:bluetooth$$', s: '$$mdi:usb$$', type: toggle}
  - $$mdi:progress-download$$
  - F7
  - F8
  - F9
  - F12
  - {t: BT, h: '0'}
  - {t: BT, h: '1'}
  - {t: BT, h: '2'}
  - {t: BT, h: '3'}
  - {t: BT, h: '4'}
  - ''
  - F4
  - F5
  - F6
  - F11
  - ''
  - ''
  - {t: '$$mdi:bluetooth$$', s: '$$mdi:close-thick$$', type: text_with_symbol}
  - ''
  - ''
  - ''
  - F1
  - F2
  - F3
  - F10
  - ''
  - ''
  - ''
  - ''
  - ''
  - {type: held}
combos:
- p: [13, 16]
  k: $$mdi:apple-keyboard-caps$$

  l: [DEF]
- p: [20, 21]
  k: $$mdi:content-cut$$
  l: [DEF]
- p: [21, 22]
  k: $$mdi:content-copy$$
  l: [DEF]
- p: [22, 23]
  k: $$mdi:content-paste$$
  l: [DEF]
- p: [14, 15]
  k: $$mdi:repeat$$
  draw_separate: true
- p: [10, 11]
  k: $$mdi:content-save$$
  l: [DEF]
- p: [0, 1]
  k: ESCAPE
  l: [DEF]
- p: [1, 2]
  k: $$mdi:close-box-outline$$
  l: [DEF]
- p: [1, 2, 0]
  k: $$mdi:pistol$$
  l: [DEF]
  draw_separate: true
