name: draw keymap

on:
  workflow_dispatch:  # can be triggered manually
  push:               # automatically run on changes to following paths
    paths:
      - ".github/workflows/doc.yml"
      - "keymap_img/temper_keymap_config.yaml"
      - "keymap_img/temper.yaml"
      - "config/*.keymap"
      - "config/*.json"

jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write  # allow workflow to commit to the repo
    with:
      commit_message: "[Draw] ${{ github.event.head_commit.message }}"
      # amend_commit: true
      # fail_on_error: true
      install_branch: "main"
      keymap_patterns: "config/temper.keymap"
      config_path: "keymap_img/temper_keymap_config.yaml"
      json_path: "config"
      output_folder: "keymap_img"                          # path to save produced SVG and keymap YAML files
      parse_args: "temper:'-c 10'"
      draw_args: "temper:' -s DEF NUM NAV FUN'"   # map of extra args to pass to `keymap draw`, e.g. "corne:'-k corne_rotated' cradio:'-k paroxysm'"
